// Atomic first-generation reversal of untouched active reservation transfers.
// Never changes shipped history, prices, money, or inventory_movements.
import { previewUntouchedReservationUndo } from './catalog-reserved-undo-preview.ts'

const stockFingerprint="(SELECT COALESCE(json_group_array(json_array(id,variant_id,inventory_source,quantity,reserved_quantity,updated_at,last_source_ref)),'[]') FROM (SELECT id,variant_id,inventory_source,quantity,reserved_quantity,updated_at,last_source_ref FROM inventory_stock WHERE variant_id IN (s.id,k.id) ORDER BY id))"
const reservationFingerprint="(SELECT COALESCE(json_group_array(json_array(id,variant_id,inventory_source,quantity,status,updated_at,order_id,order_item_id)),'[]') FROM (SELECT id,variant_id,inventory_source,quantity,status,updated_at,order_id,order_item_id FROM inventory_reservations WHERE variant_id IN (s.id,k.id) ORDER BY id))"
const headGuard=[
 "julianday(c.created_at) IS NOT NULL",
 "AND NOT EXISTS(SELECT 1 FROM catalog_variant_merge_generation_events e WHERE e.source_variant_id IN(s.id,k.id))",
 "AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidations x WHERE x.id<>c.id AND (x.target_variant_id IN(s.id,k.id) OR x.source_variant_id=k.id))",
 "AND EXISTS(SELECT 1 FROM catalog_variant_consolidation_validations v WHERE v.consolidation_id=c.id AND v.passed=1)",
 "AND EXISTS(SELECT 1 FROM catalog_variant_consolidation_reservation_validations v WHERE v.consolidation_id=c.id AND v.passed=1)",
 "AND c.source_reserved_quantity>0",
 "AND (SELECT COALESCE(SUM(r.quantity),-1) FROM catalog_variant_consolidation_reservation_rows r WHERE r.consolidation_id=c.id)=c.source_reserved_quantity",
 "AND (SELECT COALESCE(SUM(l.source_reserved_before),-1) FROM catalog_variant_consolidation_stock_rows l WHERE l.consolidation_id=c.id)=c.source_reserved_quantity",
 "AND (SELECT COUNT(*) FROM catalog_variant_consolidation_stock_rows l WHERE l.consolidation_id=c.id)>0",
 "AND (SELECT COUNT(*) FROM catalog_variant_consolidation_stock_rows l WHERE l.consolidation_id=c.id)=(SELECT COUNT(*) FROM catalog_variant_consolidation_stock_decisions d WHERE d.consolidation_id=c.id)",
 "AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidation_stock_rows l LEFT JOIN catalog_variant_consolidation_stock_decisions d ON d.consolidation_id=l.consolidation_id AND d.inventory_source=l.inventory_source LEFT JOIN inventory_stock ss ON ss.id=l.source_stock_id LEFT JOIN inventory_stock ks ON ks.id=l.target_stock_id_before WHERE l.consolidation_id=c.id AND (d.inventory_source IS NULL OR d.decision_method<>'sum' OR d.adjustment_quantity<>0 OR l.target_stock_id_before IS NULL OR d.final_quantity<>l.source_quantity_before+l.target_quantity_before OR d.final_quantity<>l.combined_quantity_after OR l.source_reserved_before>l.source_quantity_before OR l.target_reserved_before>l.target_quantity_before OR ss.id IS NULL OR ks.id IS NULL OR ss.variant_id<>s.id OR ks.variant_id<>k.id OR ss.inventory_source<>l.inventory_source OR ks.inventory_source<>l.inventory_source OR ss.quantity<>0 OR ss.reserved_quantity<>0 OR ks.quantity<>l.combined_quantity_after OR ks.reserved_quantity<>l.source_reserved_before+l.target_reserved_before OR (SELECT COALESCE(SUM(r.quantity),0) FROM inventory_reservations r WHERE r.variant_id=k.id AND r.status='active' AND r.inventory_source=l.inventory_source)<>ks.reserved_quantity OR (SELECT COALESCE(SUM(r.quantity),0) FROM catalog_variant_consolidation_reservation_rows r WHERE r.consolidation_id=c.id AND r.inventory_source=l.inventory_source)<>l.source_reserved_before OR ss.last_source_ref IS NOT ('catalog-consolidation:'||s.id||'->'||k.id) OR ks.last_source_ref IS NOT ('catalog-consolidation:'||s.id||'->'||k.id) OR julianday(ss.updated_at) IS NULL OR julianday(ks.updated_at) IS NULL OR julianday(ss.updated_at)>julianday(c.created_at) OR julianday(ks.updated_at)>julianday(c.created_at)))",
 "AND NOT EXISTS(SELECT 1 FROM inventory_stock st WHERE st.variant_id IN(s.id,k.id) AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidation_stock_rows l WHERE l.consolidation_id=c.id AND ((st.variant_id=s.id AND st.id=l.source_stock_id) OR (st.variant_id=k.id AND st.id=l.target_stock_id_before))))",
 "AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidation_reservation_rows r LEFT JOIN inventory_reservations now ON now.id=r.reservation_id LEFT JOIN order_items oi ON oi.id=r.order_item_id LEFT JOIN orders o ON o.id=r.order_id WHERE r.consolidation_id=c.id AND (r.original_variant_id<>s.id OR r.keeper_variant_id<>k.id OR now.id IS NULL OR now.variant_id<>k.id OR now.status<>'active' OR now.quantity<>r.quantity OR now.inventory_source<>r.inventory_source OR now.order_id<>r.order_id OR now.order_item_id<>r.order_item_id OR julianday(now.updated_at) IS NULL OR julianday(now.updated_at)<>julianday(c.created_at) OR oi.id IS NULL OR oi.variant_id<>k.id OR oi.order_id<>r.order_id OR oi.source_type<>r.inventory_source OR oi.stock_writeoff_status<>'reserved' OR COALESCE(oi.is_workshop,0)<>0 OR oi.quantity<>(SELECT COALESCE(SUM(x.quantity),0) FROM catalog_variant_consolidation_reservation_rows x WHERE x.consolidation_id=c.id AND x.order_item_id=oi.id) OR julianday(oi.created_at) IS NULL OR julianday(oi.created_at)>=julianday(c.created_at) OR o.id IS NULL OR o.order_status<>'active' OR COALESCE(o.shipping_status,'not_sent')='sent' OR julianday(o.updated_at) IS NULL OR julianday(o.updated_at)>=julianday(c.created_at) OR EXISTS(SELECT 1 FROM return_items ret WHERE ret.order_item_id=oi.id) OR EXISTS(SELECT 1 FROM exchanges ex WHERE ex.old_order_item_id=oi.id OR ex.new_order_item_id=oi.id) OR EXISTS(SELECT 1 FROM exchange_items ex WHERE ex.order_item_id=oi.id)))",
 "AND NOT EXISTS(SELECT 1 FROM inventory_reservations r WHERE r.status='active' AND r.variant_id=s.id)",
 "AND NOT EXISTS(SELECT 1 FROM inventory_reservations r WHERE r.variant_id IN(s.id,k.id) AND (julianday(r.updated_at) IS NULL OR (julianday(r.updated_at)>=julianday(c.created_at) AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidation_reservation_rows x WHERE x.consolidation_id=c.id AND x.reservation_id=r.id AND r.variant_id=k.id AND r.status='active' AND julianday(r.updated_at)=julianday(c.created_at)))))",
 "AND NOT EXISTS(SELECT 1 FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.variant_id IN(s.id,k.id) AND (julianday(oi.created_at) IS NULL OR julianday(o.updated_at) IS NULL OR MAX(julianday(oi.created_at),julianday(o.updated_at))>=julianday(c.created_at)))",
 "AND NOT EXISTS(SELECT 1 FROM inventory_movements m WHERE m.variant_id IN(s.id,k.id) AND (julianday(m.created_at) IS NULL OR julianday(m.created_at)>=julianday(c.created_at)))",
 "AND NOT EXISTS(SELECT 1 FROM inventory_stock_checks ch WHERE ch.variant_id IN(s.id,k.id) AND (julianday(ch.checked_at) IS NULL OR julianday(ch.checked_at)>=julianday(c.created_at)))",
 "AND NOT EXISTS(SELECT 1 FROM workshop_tasks w WHERE w.variant_id IN(s.id,k.id) AND w.status='active')",
 "AND NOT EXISTS(SELECT 1 FROM inventory_lifecycle_events le WHERE le.variant_id IN(s.id,k.id) AND le.status IN('pending','applied'))",
 "AND NOT EXISTS(SELECT 1 FROM inventory_stocktake_items i JOIN inventory_stocktake_sessions ss ON ss.id=i.session_id WHERE i.variant_id IN(s.id,k.id) AND ss.status='active')",
 "AND NOT EXISTS(SELECT 1 FROM inventory_transfer_items i JOIN inventory_transfer_documents t ON t.id=i.transfer_id WHERE i.variant_id IN(s.id,k.id) AND t.status='applied')",
 "AND NOT EXISTS(SELECT 1 FROM order_items oi WHERE oi.variant_id IN(s.id,k.id) AND (EXISTS(SELECT 1 FROM return_items ret WHERE ret.order_item_id=oi.id) OR EXISTS(SELECT 1 FROM exchanges ex WHERE ex.old_order_item_id=oi.id OR ex.new_order_item_id=oi.id) OR EXISTS(SELECT 1 FROM exchange_items ex WHERE ex.order_item_id=oi.id)))"
].join(" ")

export async function undoUntouchedReservationConsolidation(
 db:D1Database,id:number,actor:string,reason:string,expectedToken:string
){
 if(!Number.isSafeInteger(id)||id<=0)throw new Error('Укажите корректное объединение.')
 const who=(actor||'').trim(),why=(reason||'').trim()
 if(!who||why.length<12||why.length>500)throw new Error('Требуется администратор и причина исправления (12–500 символов).')
 if(!expectedToken)throw new Error('Проверка заказа и резервов обязательна.')
 const review=await previewUntouchedReservationUndo(db,id)
 if(!review.canRestoreUntouchedReservations)
  throw new Error('Отмена заблокирована: '+review.blockers.map(x=>x.message).join('; '))
 if(review.stateToken!==expectedToken)throw new Error('Заказы, резервы или остатки изменились. Выполните проверку заново.')
 const token=JSON.parse(expectedToken) as {mergedAt:string;sourceUpdated:string;keeperUpdated:string;stocks:unknown[];reservations:unknown[]}
 const now=new Date().toISOString(),ref='catalog-reserved-undo:'+id
 const event=db.prepare("INSERT INTO catalog_variant_merge_generation_events(root_consolidation_id,source_variant_id,target_variant_id,generation,event_kind,reason,created_by,created_at) SELECT c.id,s.id,k.id,2,'undo',?,?,? FROM catalog_variant_consolidations c JOIN catalog_variants s ON s.id=c.source_variant_id JOIN catalog_variants k ON k.id=c.target_variant_id WHERE c.id=? AND s.id=? AND k.id=? AND c.created_at=? AND s.is_active=0 AND k.is_active=1 AND s.updated_at=? AND k.updated_at=? AND s.product_id=c.product_id AND k.product_id=c.product_id AND "+headGuard+" AND "+stockFingerprint+"=? AND "+reservationFingerprint+"=?")
  .bind(why,who,now,id,review.sourceId,review.keeperId,token.mergedAt,token.sourceUpdated,token.keeperUpdated,JSON.stringify(token.stocks),JSON.stringify(token.reservations))
 const location=db.prepare("INSERT INTO catalog_variant_reserved_undo_locations(generation_event_id,inventory_source,source_stock_id,keeper_stock_id,keeper_quantity_merged,keeper_reserved_merged,source_quantity_restored,keeper_quantity_restored,source_reserved_restored,keeper_reserved_restored) SELECT e.id,l.inventory_source,l.source_stock_id,l.target_stock_id_before,l.combined_quantity_after,l.source_reserved_before+l.target_reserved_before,l.source_quantity_before,l.target_quantity_before,l.source_reserved_before,l.target_reserved_before FROM catalog_variant_merge_generation_events e JOIN catalog_variant_consolidation_stock_rows l ON l.consolidation_id=e.root_consolidation_id JOIN inventory_stock ss ON ss.id=l.source_stock_id JOIN inventory_stock ks ON ks.id=l.target_stock_id_before WHERE e.root_consolidation_id=? AND e.source_variant_id=? AND e.target_variant_id=? AND e.generation=2 AND e.created_at=? AND ss.quantity=0 AND ss.reserved_quantity=0 AND ks.quantity=l.combined_quantity_after AND ks.reserved_quantity=l.source_reserved_before+l.target_reserved_before")
  .bind(id,review.sourceId,review.keeperId,now)
 const audit=db.prepare("INSERT INTO catalog_variant_reserved_undo_reservations(generation_event_id,reservation_id,order_id,order_item_id,inventory_source,quantity,source_variant_id,keeper_variant_id) SELECT e.id,a.reservation_id,a.order_id,a.order_item_id,a.inventory_source,a.quantity,e.source_variant_id,e.target_variant_id FROM catalog_variant_merge_generation_events e JOIN catalog_variant_consolidation_reservation_rows a ON a.consolidation_id=e.root_consolidation_id JOIN inventory_reservations r ON r.id=a.reservation_id JOIN order_items oi ON oi.id=a.order_item_id JOIN orders o ON o.id=a.order_id WHERE e.root_consolidation_id=? AND e.source_variant_id=? AND e.target_variant_id=? AND e.generation=2 AND e.created_at=? AND r.variant_id=e.target_variant_id AND r.status='active' AND r.quantity=a.quantity AND r.order_id=a.order_id AND r.order_item_id=a.order_item_id AND r.inventory_source=a.inventory_source AND oi.variant_id=e.target_variant_id AND oi.order_id=a.order_id AND oi.source_type=a.inventory_source AND oi.stock_writeoff_status='reserved' AND COALESCE(oi.is_workshop,0)=0 AND o.order_status='active' AND COALESCE(o.shipping_status,'not_sent')<>'sent' AND julianday(r.updated_at)=julianday(?)")
  .bind(id,review.sourceId,review.keeperId,now,token.mergedAt)
 const activate=db.prepare("UPDATE catalog_variants SET is_active=1,updated_at=? WHERE id=? AND is_active=0 AND updated_at=? AND EXISTS(SELECT 1 FROM catalog_variant_merge_generation_events e WHERE e.root_consolidation_id=? AND e.source_variant_id=? AND e.generation=2 AND e.event_kind='undo' AND e.created_at=?)")
  .bind(now,review.sourceId,token.sourceUpdated,id,review.sourceId,now)
 const keeper=db.prepare("UPDATE inventory_stock SET quantity=(SELECT a.keeper_quantity_restored FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.keeper_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=?),reserved_quantity=(SELECT a.keeper_reserved_restored FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.keeper_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=?),updated_at=?,last_action='Отмена объединения с резервом',last_source_ref=? WHERE variant_id=? AND EXISTS(SELECT 1 FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.keeper_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=? AND inventory_stock.quantity=a.keeper_quantity_merged AND inventory_stock.reserved_quantity=a.keeper_reserved_merged)")
  .bind(id,now,id,now,now,ref,review.keeperId,id,now)
 const source=db.prepare("UPDATE inventory_stock SET quantity=(SELECT a.source_quantity_restored FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.source_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=?),reserved_quantity=(SELECT a.source_reserved_restored FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.source_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=?),updated_at=?,last_action='Отмена объединения с резервом',last_source_ref=? WHERE variant_id=? AND quantity=0 AND reserved_quantity=0 AND EXISTS(SELECT 1 FROM catalog_variants v WHERE v.id=inventory_stock.variant_id AND v.is_active=1) AND EXISTS(SELECT 1 FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.source_stock_id=inventory_stock.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=?)")
  .bind(id,now,id,now,now,ref,review.sourceId,id,now)
 const restores=db.prepare("UPDATE inventory_reservations SET variant_id=?,updated_at=? WHERE variant_id=? AND status='active' AND julianday(updated_at)=julianday(?) AND EXISTS(SELECT 1 FROM catalog_variant_reserved_undo_reservations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE a.reservation_id=inventory_reservations.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=? AND a.source_variant_id=? AND a.keeper_variant_id=? AND a.order_id=inventory_reservations.order_id AND a.order_item_id=inventory_reservations.order_item_id AND a.quantity=inventory_reservations.quantity AND a.inventory_source=inventory_reservations.inventory_source)")
  .bind(review.sourceId,now,review.keeperId,token.mergedAt,id,now,review.sourceId,review.keeperId)
 const items=db.prepare("UPDATE order_items SET variant_id=? WHERE variant_id=? AND EXISTS(SELECT 1 FROM catalog_variant_reserved_undo_reservations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id JOIN orders o ON o.id=a.order_id WHERE a.order_item_id=order_items.id AND e.root_consolidation_id=? AND e.generation=2 AND e.created_at=? AND a.source_variant_id=? AND o.order_status='active' AND COALESCE(o.shipping_status,'not_sent')<>'sent' AND julianday(o.updated_at)<julianday(?) AND order_items.source_type=a.inventory_source AND order_items.stock_writeoff_status='reserved' AND COALESCE(order_items.is_workshop,0)=0 AND order_items.quantity=(SELECT COALESCE(SUM(x.quantity),0) FROM catalog_variant_reserved_undo_reservations x WHERE x.generation_event_id=e.id AND x.order_item_id=order_items.id) AND NOT EXISTS(SELECT 1 FROM catalog_variant_reserved_undo_reservations x LEFT JOIN inventory_reservations r ON r.id=x.reservation_id WHERE x.generation_event_id=e.id AND x.order_item_id=order_items.id AND (r.id IS NULL OR r.variant_id<>? OR r.status<>'active' OR r.quantity<>x.quantity OR r.order_id<>x.order_id OR r.order_item_id<>x.order_item_id)))")
  .bind(review.sourceId,review.keeperId,id,now,review.sourceId,token.mergedAt,review.sourceId)
 const proof=db.prepare("INSERT INTO catalog_variant_reserved_undo_validations(generation_event_id,root_consolidation_id,source_variant_id,keeper_variant_id,validated_locations,validated_reservations,physical_total,reserve_total,passed,checked_by,checked_at) SELECT COALESCE((SELECT e.id FROM catalog_variant_merge_generation_events e WHERE e.root_consolidation_id=? AND e.source_variant_id=? AND e.generation=2 AND e.created_at=?),-1),c.id,c.source_variant_id,c.target_variant_id,(SELECT COUNT(*) FROM catalog_variant_consolidation_stock_rows l WHERE l.consolidation_id=c.id),(SELECT COUNT(*) FROM catalog_variant_consolidation_reservation_rows a WHERE a.consolidation_id=c.id),(SELECT COALESCE(SUM(a.source_quantity_restored+a.keeper_quantity_restored),0) FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE e.root_consolidation_id=c.id AND e.generation=2 AND e.created_at=?),(SELECT COALESCE(SUM(a.source_reserved_restored+a.keeper_reserved_restored),0) FROM catalog_variant_reserved_undo_locations a JOIN catalog_variant_merge_generation_events e ON e.id=a.generation_event_id WHERE e.root_consolidation_id=c.id AND e.generation=2 AND e.created_at=?),CASE WHEN s.is_active=1 AND k.is_active=1 AND s.updated_at=? AND k.updated_at=? AND NOT EXISTS(SELECT 1 FROM catalog_variant_consolidation_stock_rows l LEFT JOIN inventory_stock ss ON ss.id=l.source_stock_id LEFT JOIN inventory_stock ks ON ks.id=l.target_stock_id_before WHERE l.consolidation_id=c.id AND (ss.updated_at IS NOT ? OR ks.updated_at IS NOT ? OR ss.last_source_ref IS NOT ? OR ks.last_source_ref IS NOT ?)) THEN 1 ELSE 0 END,?,? FROM catalog_variant_consolidations c JOIN catalog_variants s ON s.id=c.source_variant_id JOIN catalog_variants k ON k.id=c.target_variant_id WHERE c.id=?")
  .bind(id,review.sourceId,now,now,now,now,token.keeperUpdated,now,now,ref,ref,who,now,id)
 let result:D1Result[]
 try{result=await db.batch([event,location,audit,activate,keeper,source,restores,items,proof])}
 catch{throw new Error('Отмена не выполнена: склад, резерв или заказ изменился. Обновите проверку.')}
 if(result.length!==9||result[0].meta?.changes!==1
    ||result[1].meta?.changes!==review.locations.length
    ||result[2].meta?.changes!==review.reservationCount
    ||result[3].meta?.changes!==1
    ||result[4].meta?.changes!==review.locations.length
    ||result[5].meta?.changes!==review.locations.length
    ||result[6].meta?.changes!==review.reservationCount||result[8].meta?.changes!==1)
  throw new Error('Результат требует сверки журнала. Не повторяйте операцию вслепую.')
 return {ok:true,undone:true,generation:2,consolidationId:id,
  sourceId:review.sourceId,keeperId:review.keeperId,
  restoredReservations:review.reservationCount,physicalDelta:0,reservedDelta:0,
  message:'Незатронутые открытые резервы возвращены исходному SKU. История и количество сохранены.'}
}
