PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS reference_values (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL,
  value TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reference_values_kind_value
  ON reference_values(kind, value);

INSERT INTO managers (name, is_active, created_at, updated_at) VALUES
  ('СЫМБАТ', 1, datetime('now'), datetime('now')),
  ('АСЕЛЬ', 1, datetime('now'), datetime('now')),
  ('ГАЗИЗА', 1, datetime('now'), datetime('now')),
  ('ГУЛНУР', 1, datetime('now'), datetime('now')),
  ('ЖАНЕРКЕ', 1, datetime('now'), datetime('now')),
  ('МАКПАЛ', 1, datetime('now'), datetime('now')),
  ('САИДА', 1, datetime('now'), datetime('now'))
ON CONFLICT(name) DO UPDATE SET
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;

INSERT INTO reference_values (kind, value, is_active, sort_order, created_at, updated_at) VALUES
  ('city', 'АЛМАТЫ', 1, 1, datetime('now'), datetime('now')),
  ('city', 'АСТАНА', 1, 2, datetime('now'), datetime('now')),
  ('city', 'ШЫМКЕНТ', 1, 3, datetime('now'), datetime('now')),
  ('city', 'КАРАГАНДА', 1, 4, datetime('now'), datetime('now')),
  ('city', 'АКТОБЕ', 1, 5, datetime('now'), datetime('now')),
  ('city', 'ТАРАЗ', 1, 6, datetime('now'), datetime('now')),
  ('city', 'ПАВЛОДАР', 1, 7, datetime('now'), datetime('now')),
  ('city', 'СЕМЕЙ', 1, 8, datetime('now'), datetime('now')),
  ('city', 'УСТЬ-КАМЕНОГОРСК', 1, 9, datetime('now'), datetime('now')),
  ('city', 'ҚЫЗЫЛОРДА', 1, 10, datetime('now'), datetime('now')),
  ('city', 'КОСТАНАЙ', 1, 11, datetime('now'), datetime('now')),
  ('city', 'АТЫРАУ', 1, 12, datetime('now'), datetime('now')),
  ('city', 'АКТАУ', 1, 13, datetime('now'), datetime('now')),
  ('city', 'ТАЛДЫКОРГАН', 1, 14, datetime('now'), datetime('now')),
  ('city', 'ТУРКЕСТАН', 1, 15, datetime('now'), datetime('now')),
  ('city', 'ПЕТРОПАВЛОВСК', 1, 16, datetime('now'), datetime('now')),
  ('city', 'КОКШЕТАУ', 1, 17, datetime('now'), datetime('now')),
  ('city', 'ЖЕЗКАЗГАН', 1, 18, datetime('now'), datetime('now')),
  ('city', 'ТЕМИРТАУ', 1, 19, datetime('now'), datetime('now')),
  ('city', 'ЭКИБАСТУЗ', 1, 20, datetime('now'), datetime('now')),
  ('city', 'БАЛХАШ', 1, 21, datetime('now'), datetime('now')),
  ('city', 'РУДНЫЙ', 1, 22, datetime('now'), datetime('now')),
  ('city', 'САТПАЕВ', 1, 23, datetime('now'), datetime('now')),
  ('city', 'РИДДЕР', 1, 24, datetime('now'), datetime('now')),
  ('city', 'КАСКЕЛЕН', 1, 25, datetime('now'), datetime('now')),
  ('city', 'ТАЛГАР', 1, 26, datetime('now'), datetime('now')),
  ('city', 'ЕСИК', 1, 27, datetime('now'), datetime('now')),
  ('city', 'ШЕЛЕК', 1, 28, datetime('now'), datetime('now')),
  ('city', 'САРЫАГАШ', 1, 29, datetime('now'), datetime('now')),
  ('city', 'ШИЕЛИ', 1, 30, datetime('now'), datetime('now')),
  ('city', 'ЖАНАКОРГАН', 1, 31, datetime('now'), datetime('now')),
  ('city', 'АРАЛЬСК', 1, 32, datetime('now'), datetime('now')),
  ('city', 'БАЙКОНУР', 1, 33, datetime('now'), datetime('now')),
  ('city', 'УРАЛЬСК', 1, 34, datetime('now'), datetime('now')),
  ('city', 'АКСАЙ', 1, 35, datetime('now'), datetime('now')),
  ('city', 'ЖАРКЕНТ', 1, 36, datetime('now'), datetime('now')),
  ('city', 'КЕНТАУ', 1, 37, datetime('now'), datetime('now')),
  ('city', 'ЛЕНГЕР', 1, 38, datetime('now'), datetime('now')),
  ('city', 'ШУ', 1, 39, datetime('now'), datetime('now')),
  ('city', 'КАРАТАУ', 1, 40, datetime('now'), datetime('now')),
  ('city', 'АКСУКЕНТ', 1, 41, datetime('now'), datetime('now')),
  ('city', 'ЖЕТЫСАЙ', 1, 42, datetime('now'), datetime('now')),
  ('city', 'ЖАНАОЗЕН', 1, 43, datetime('now'), datetime('now')),
  ('city', 'КУЛЬСАРЫ', 1, 44, datetime('now'), datetime('now')),
  ('city', 'ХРОМТАУ', 1, 45, datetime('now'), datetime('now')),
  ('city', 'ШАРДАРА', 1, 46, datetime('now'), datetime('now')),
  ('delivery_type', 'ПОЧТА', 1, 1, datetime('now'), datetime('now')),
  ('delivery_type', 'КУРЬЕР', 1, 2, datetime('now'), datetime('now')),
  ('delivery_type', 'САМОВЫВОЗ', 1, 3, datetime('now'), datetime('now')),
  ('delivery_type', 'МЕЖГОРОД', 1, 4, datetime('now'), datetime('now')),
  ('payment_method', 'КАСПИ МАГАЗИН', 1, 1, datetime('now'), datetime('now')),
  ('payment_method', 'НАЛИЧКА', 1, 2, datetime('now'), datetime('now')),
  ('payment_method', 'ТЕРМИНАЛ', 1, 3, datetime('now'), datetime('now')),
  ('payment_method', 'ХАЛЫК ПЕРЕВОД', 1, 4, datetime('now'), datetime('now')),
  ('payment_method', 'KASPI PAY', 1, 5, datetime('now'), datetime('now')),
  ('color', 'БЕЖЕВЫЙ', 1, 1, datetime('now'), datetime('now')),
  ('color', 'БЕЛЫЙ', 1, 2, datetime('now'), datetime('now')),
  ('color', 'АЙВОРИ', 1, 3, datetime('now'), datetime('now')),
  ('color', 'БОРДОВЫЙ', 1, 4, datetime('now'), datetime('now')),
  ('color', 'ВЕРБЛЮЖКА', 1, 5, datetime('now'), datetime('now')),
  ('color', 'ГОЛУБОЙ', 1, 6, datetime('now'), datetime('now')),
  ('color', 'ЖЕЛТЫЙ', 1, 7, datetime('now'), datetime('now')),
  ('color', 'ЗЕЛЕНЫЙ', 1, 8, datetime('now'), datetime('now')),
  ('color', 'ИЗУМРУД', 1, 9, datetime('now'), datetime('now')),
  ('color', 'КОРИЧНЕВЫЙ', 1, 10, datetime('now'), datetime('now')),
  ('color', 'КОФЕ', 1, 11, datetime('now'), datetime('now')),
  ('color', 'КРАСНЫЙ', 1, 12, datetime('now'), datetime('now')),
  ('color', 'МОКРЫЙ АСФАЛЬТ', 1, 13, datetime('now'), datetime('now')),
  ('color', 'ОРАНЖЕВЫЙ', 1, 14, datetime('now'), datetime('now')),
  ('color', 'РОЗОВЫЙ', 1, 15, datetime('now'), datetime('now')),
  ('color', 'СВЕТЛО-БЕЖЕВЫЙ', 1, 16, datetime('now'), datetime('now')),
  ('color', 'СВЕТЛЫЙ', 1, 17, datetime('now'), datetime('now')),
  ('color', 'СЕРЫЙ', 1, 18, datetime('now'), datetime('now')),
  ('color', 'СИНИЙ', 1, 19, datetime('now'), datetime('now')),
  ('color', 'ТЕМНО-СИНИЙ', 1, 20, datetime('now'), datetime('now')),
  ('color', 'ТЕМНЫЙ', 1, 21, datetime('now'), datetime('now')),
  ('color', 'ТЕМНЫЙ МОКРЫЙ АСФАЛЬТ', 1, 22, datetime('now'), datetime('now')),
  ('color', 'ХАКИ', 1, 23, datetime('now'), datetime('now')),
  ('color', 'ЧЕРНЫЙ', 1, 24, datetime('now'), datetime('now')),
  ('color', 'ШОКОЛАД', 1, 25, datetime('now'), datetime('now')),
  ('material', 'ДЖИНСА', 1, 1, datetime('now'), datetime('now')),
  ('material', 'ЗАМША ВЕЛЮР', 1, 2, datetime('now'), datetime('now')),
  ('material', 'КАШЕМИР', 1, 3, datetime('now'), datetime('now')),
  ('material', 'МЯГКАЯ ТКАНЬ', 1, 4, datetime('now'), datetime('now')),
  ('length', 'СТАНДАРТ', 1, 1, datetime('now'), datetime('now')),
  ('length', 'УКОРОЧЕННЫЙ', 1, 2, datetime('now'), datetime('now')),
  ('length', 'ДЛИННЫЙ', 1, 3, datetime('now'), datetime('now')),
  ('size', '42', 1, 1, datetime('now'), datetime('now')),
  ('size', '44', 1, 2, datetime('now'), datetime('now')),
  ('size', '46', 1, 3, datetime('now'), datetime('now')),
  ('size', '48', 1, 4, datetime('now'), datetime('now')),
  ('size', '50', 1, 5, datetime('now'), datetime('now')),
  ('size', '52', 1, 6, datetime('now'), datetime('now')),
  ('size', '54', 1, 7, datetime('now'), datetime('now')),
  ('size', '56', 1, 8, datetime('now'), datetime('now')),
  ('size', '58', 1, 9, datetime('now'), datetime('now')),
  ('size', '60', 1, 10, datetime('now'), datetime('now')),
  ('size', '62', 1, 11, datetime('now'), datetime('now')),
  ('size', '64', 1, 12, datetime('now'), datetime('now')),
  ('size', '66', 1, 13, datetime('now'), datetime('now')),
  ('size', '68', 1, 14, datetime('now'), datetime('now')),
  ('child_age', '1', 1, 1, datetime('now'), datetime('now')),
  ('child_age', '2', 1, 2, datetime('now'), datetime('now')),
  ('child_age', '3', 1, 3, datetime('now'), datetime('now')),
  ('child_age', '4', 1, 4, datetime('now'), datetime('now')),
  ('child_age', '5', 1, 5, datetime('now'), datetime('now')),
  ('child_age', '6', 1, 6, datetime('now'), datetime('now')),
  ('child_age', '7', 1, 7, datetime('now'), datetime('now')),
  ('child_age', '8', 1, 8, datetime('now'), datetime('now')),
  ('child_age', '9', 1, 9, datetime('now'), datetime('now')),
  ('child_age', '10', 1, 10, datetime('now'), datetime('now'))
ON CONFLICT(kind, value) DO NOTHING;

INSERT INTO catalog_products (name, category, is_active, created_at, updated_at) VALUES
  ('АЙДАЙ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('АЙДАР ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('АЙНУРЫМ АЙ КОЙЛЕК', 'adult', 1, datetime('now'), datetime('now')),
  ('АКСЕСУАР', 'adult', 1, datetime('now'), datetime('now')),
  ('АЛАН БОМБЕР', 'adult', 1, datetime('now'), datetime('now')),
  ('АМИР БОМБЕР', 'adult', 1, datetime('now'), datetime('now')),
  ('АРУ КӨЙЛЕК', 'adult', 1, datetime('now'), datetime('now')),
  ('БАЙСАЛ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('БАСКА', 'adult', 1, datetime('now'), datetime('now')),
  ('БАЯН СҰЛУ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('БАЯН СҰЛУ ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('БИКЕШ КӨЙЛЕК', 'adult', 1, datetime('now'), datetime('now')),
  ('ВОРОТНИК', 'adult', 1, datetime('now'), datetime('now')),
  ('ДАРА ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('ДОКЕР', 'adult', 1, datetime('now'), datetime('now')),
  ('ЕҢЛІК ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('ЗЕЙНЕ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('КЕБЕК ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('КЕПКА', 'adult', 1, datetime('now'), datetime('now')),
  ('КЕРБЕЗ КОЙЛЕК', 'adult', 1, datetime('now'), datetime('now')),
  ('КОЙЛЕК', 'adult', 1, datetime('now'), datetime('now')),
  ('КОРСЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('ҚАЗЫНА ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('ҚОЗЫ КӨРПЕШ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('ҚОЗЫ КӨРПЕШ ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('ҚОРЛАН ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('НӘЗІК КӨЙЛЕГІ', 'adult', 1, datetime('now'), datetime('now')),
  ('ОРАМАЛ', 'adult', 1, datetime('now'), datetime('now')),
  ('САРДАР ШАПАН', 'adult', 1, datetime('now'), datetime('now')),
  ('САУКЕЛЕ', 'adult', 1, datetime('now'), datetime('now')),
  ('САУЛЕТ ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('ТАҚИЯ', 'adult', 1, datetime('now'), datetime('now')),
  ('ТҰМАР ЖИЛЕТ', 'adult', 1, datetime('now'), datetime('now')),
  ('УКРАШЕНИЕ', 'adult', 1, datetime('now'), datetime('now'))
ON CONFLICT(name) DO UPDATE SET
  category = excluded.category,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;
